name: gz-docs
channels:
  - conda-forge
dependencies:
  - docutils<0.18
  - fontconfig
  - freetype
  - geos
  - graphviz
  - h5py>=2.9=mpi*
  - lxml
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - numpydoc
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - pyyaml
  - scipy
  - sphinx
  - sphinx-argparse
  - sphinx_rtd_theme
  - texlive-core
  - pip:
     - icesat2-toolkit
     - ..
