# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python on pull request

on:
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies for Linux
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev libproj-dev proj-data proj-bin \
            libgeos-dev libhdf5-dev libnetcdf-dev
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        pip install --upgrade pip
        pip install numpy
        pip install zarr
        pip install pandas
        pip install --no-deps git+https://github.com/tsutterley/read-ICESat-2.git
        pip install --no-deps git+https://github.com/tsutterley/pyTMD.git
        pip install .
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Install dependencies for MacOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install proj@7
        brew install geos
        brew install gdal
        brew install hdf5
        brew install netcdf
        brew install pkg-config
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install cython
        pip install numpy
        pip install zarr
        pip install pandas
        export LDFLAGS="-L/usr/local/opt/proj@7/lib"
        export CPPFLAGS="-I/usr/local/opt/proj@7/include"
        export ACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/proj@7/lib/pkgconfig"
        pip install --no-deps git+https://github.com/tsutterley/read-ICESat-2.git
        pip install --no-deps git+https://github.com/tsutterley/pyTMD.git
        pip install .
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
